/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TestLazyRouteImport = createFileRoute('/test')()
const KpistatsLazyRouteImport = createFileRoute('/kpistats')()
const GraphLazyRouteImport = createFileRoute('/graph')()
const ChartsLazyRouteImport = createFileRoute('/charts')()
const BarsLazyRouteImport = createFileRoute('/bars')()
const IndexLazyRouteImport = createFileRoute('/')()
const KpistatsKpistat4LazyRouteImport = createFileRoute('/kpistats/kpistat-4')()
const KpistatsKpistat3LazyRouteImport = createFileRoute('/kpistats/kpistat-3')()
const KpistatsKpistat2LazyRouteImport = createFileRoute('/kpistats/kpistat-2')()
const KpistatsKpistat1LazyRouteImport = createFileRoute('/kpistats/kpistat-1')()
const GraphGraph2LazyRouteImport = createFileRoute('/graph/graph-2')()
const GraphGraph1LazyRouteImport = createFileRoute('/graph/graph-1')()
const ChartsCircle6LazyRouteImport = createFileRoute('/charts/circle-6')()
const ChartsCircle5LazyRouteImport = createFileRoute('/charts/circle-5')()
const ChartsCircle4LazyRouteImport = createFileRoute('/charts/circle-4')()
const ChartsCircle3LazyRouteImport = createFileRoute('/charts/circle-3')()
const ChartsCircle2LazyRouteImport = createFileRoute('/charts/circle-2')()
const ChartsCircle1LazyRouteImport = createFileRoute('/charts/circle-1')()
const BarsBars4LazyRouteImport = createFileRoute('/bars/bars-4')()
const BarsBars3LazyRouteImport = createFileRoute('/bars/bars-3')()
const BarsBars2LazyRouteImport = createFileRoute('/bars/bars-2')()
const BarsBars1LazyRouteImport = createFileRoute('/bars/bars-1')()

const TestLazyRoute = TestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))
const KpistatsLazyRoute = KpistatsLazyRouteImport.update({
  id: '/kpistats',
  path: '/kpistats',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kpistats.lazy').then((d) => d.Route))
const GraphLazyRoute = GraphLazyRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/graph.lazy').then((d) => d.Route))
const ChartsLazyRoute = ChartsLazyRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts.lazy').then((d) => d.Route))
const BarsLazyRoute = BarsLazyRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bars.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const KpistatsKpistat4LazyRoute = KpistatsKpistat4LazyRouteImport.update({
  id: '/kpistat-4',
  path: '/kpistat-4',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-4.lazy').then((d) => d.Route),
)
const KpistatsKpistat3LazyRoute = KpistatsKpistat3LazyRouteImport.update({
  id: '/kpistat-3',
  path: '/kpistat-3',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-3.lazy').then((d) => d.Route),
)
const KpistatsKpistat2LazyRoute = KpistatsKpistat2LazyRouteImport.update({
  id: '/kpistat-2',
  path: '/kpistat-2',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-2.lazy').then((d) => d.Route),
)
const KpistatsKpistat1LazyRoute = KpistatsKpistat1LazyRouteImport.update({
  id: '/kpistat-1',
  path: '/kpistat-1',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-1.lazy').then((d) => d.Route),
)
const GraphGraph2LazyRoute = GraphGraph2LazyRouteImport.update({
  id: '/graph-2',
  path: '/graph-2',
  getParentRoute: () => GraphLazyRoute,
} as any).lazy(() => import('./routes/graph/graph-2.lazy').then((d) => d.Route))
const GraphGraph1LazyRoute = GraphGraph1LazyRouteImport.update({
  id: '/graph-1',
  path: '/graph-1',
  getParentRoute: () => GraphLazyRoute,
} as any).lazy(() => import('./routes/graph/graph-1.lazy').then((d) => d.Route))
const ChartsCircle6LazyRoute = ChartsCircle6LazyRouteImport.update({
  id: '/circle-6',
  path: '/circle-6',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-6.lazy').then((d) => d.Route),
)
const ChartsCircle5LazyRoute = ChartsCircle5LazyRouteImport.update({
  id: '/circle-5',
  path: '/circle-5',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-5.lazy').then((d) => d.Route),
)
const ChartsCircle4LazyRoute = ChartsCircle4LazyRouteImport.update({
  id: '/circle-4',
  path: '/circle-4',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-4.lazy').then((d) => d.Route),
)
const ChartsCircle3LazyRoute = ChartsCircle3LazyRouteImport.update({
  id: '/circle-3',
  path: '/circle-3',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-3.lazy').then((d) => d.Route),
)
const ChartsCircle2LazyRoute = ChartsCircle2LazyRouteImport.update({
  id: '/circle-2',
  path: '/circle-2',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-2.lazy').then((d) => d.Route),
)
const ChartsCircle1LazyRoute = ChartsCircle1LazyRouteImport.update({
  id: '/circle-1',
  path: '/circle-1',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-1.lazy').then((d) => d.Route),
)
const BarsBars4LazyRoute = BarsBars4LazyRouteImport.update({
  id: '/bars-4',
  path: '/bars-4',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-4.lazy').then((d) => d.Route))
const BarsBars3LazyRoute = BarsBars3LazyRouteImport.update({
  id: '/bars-3',
  path: '/bars-3',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-3.lazy').then((d) => d.Route))
const BarsBars2LazyRoute = BarsBars2LazyRouteImport.update({
  id: '/bars-2',
  path: '/bars-2',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-2.lazy').then((d) => d.Route))
const BarsBars1LazyRoute = BarsBars1LazyRouteImport.update({
  id: '/bars-1',
  path: '/bars-1',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-1.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/graph': typeof GraphLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/test': typeof TestLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/graph': typeof GraphLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/test': typeof TestLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/graph': typeof GraphLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/test': typeof TestLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bars'
    | '/charts'
    | '/graph'
    | '/kpistats'
    | '/test'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bars'
    | '/charts'
    | '/graph'
    | '/kpistats'
    | '/test'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
  id:
    | '__root__'
    | '/'
    | '/bars'
    | '/charts'
    | '/graph'
    | '/kpistats'
    | '/test'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BarsLazyRoute: typeof BarsLazyRouteWithChildren
  ChartsLazyRoute: typeof ChartsLazyRouteWithChildren
  GraphLazyRoute: typeof GraphLazyRouteWithChildren
  KpistatsLazyRoute: typeof KpistatsLazyRouteWithChildren
  TestLazyRoute: typeof TestLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpistats': {
      id: '/kpistats'
      path: '/kpistats'
      fullPath: '/kpistats'
      preLoaderRoute: typeof KpistatsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bars': {
      id: '/bars'
      path: '/bars'
      fullPath: '/bars'
      preLoaderRoute: typeof BarsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpistats/kpistat-4': {
      id: '/kpistats/kpistat-4'
      path: '/kpistat-4'
      fullPath: '/kpistats/kpistat-4'
      preLoaderRoute: typeof KpistatsKpistat4LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-3': {
      id: '/kpistats/kpistat-3'
      path: '/kpistat-3'
      fullPath: '/kpistats/kpistat-3'
      preLoaderRoute: typeof KpistatsKpistat3LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-2': {
      id: '/kpistats/kpistat-2'
      path: '/kpistat-2'
      fullPath: '/kpistats/kpistat-2'
      preLoaderRoute: typeof KpistatsKpistat2LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-1': {
      id: '/kpistats/kpistat-1'
      path: '/kpistat-1'
      fullPath: '/kpistats/kpistat-1'
      preLoaderRoute: typeof KpistatsKpistat1LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/graph/graph-2': {
      id: '/graph/graph-2'
      path: '/graph-2'
      fullPath: '/graph/graph-2'
      preLoaderRoute: typeof GraphGraph2LazyRouteImport
      parentRoute: typeof GraphLazyRoute
    }
    '/graph/graph-1': {
      id: '/graph/graph-1'
      path: '/graph-1'
      fullPath: '/graph/graph-1'
      preLoaderRoute: typeof GraphGraph1LazyRouteImport
      parentRoute: typeof GraphLazyRoute
    }
    '/charts/circle-6': {
      id: '/charts/circle-6'
      path: '/circle-6'
      fullPath: '/charts/circle-6'
      preLoaderRoute: typeof ChartsCircle6LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-5': {
      id: '/charts/circle-5'
      path: '/circle-5'
      fullPath: '/charts/circle-5'
      preLoaderRoute: typeof ChartsCircle5LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-4': {
      id: '/charts/circle-4'
      path: '/circle-4'
      fullPath: '/charts/circle-4'
      preLoaderRoute: typeof ChartsCircle4LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-3': {
      id: '/charts/circle-3'
      path: '/circle-3'
      fullPath: '/charts/circle-3'
      preLoaderRoute: typeof ChartsCircle3LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-2': {
      id: '/charts/circle-2'
      path: '/circle-2'
      fullPath: '/charts/circle-2'
      preLoaderRoute: typeof ChartsCircle2LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-1': {
      id: '/charts/circle-1'
      path: '/circle-1'
      fullPath: '/charts/circle-1'
      preLoaderRoute: typeof ChartsCircle1LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/bars/bars-4': {
      id: '/bars/bars-4'
      path: '/bars-4'
      fullPath: '/bars/bars-4'
      preLoaderRoute: typeof BarsBars4LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-3': {
      id: '/bars/bars-3'
      path: '/bars-3'
      fullPath: '/bars/bars-3'
      preLoaderRoute: typeof BarsBars3LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-2': {
      id: '/bars/bars-2'
      path: '/bars-2'
      fullPath: '/bars/bars-2'
      preLoaderRoute: typeof BarsBars2LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-1': {
      id: '/bars/bars-1'
      path: '/bars-1'
      fullPath: '/bars/bars-1'
      preLoaderRoute: typeof BarsBars1LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
  }
}

interface BarsLazyRouteChildren {
  BarsBars1LazyRoute: typeof BarsBars1LazyRoute
  BarsBars2LazyRoute: typeof BarsBars2LazyRoute
  BarsBars3LazyRoute: typeof BarsBars3LazyRoute
  BarsBars4LazyRoute: typeof BarsBars4LazyRoute
}

const BarsLazyRouteChildren: BarsLazyRouteChildren = {
  BarsBars1LazyRoute: BarsBars1LazyRoute,
  BarsBars2LazyRoute: BarsBars2LazyRoute,
  BarsBars3LazyRoute: BarsBars3LazyRoute,
  BarsBars4LazyRoute: BarsBars4LazyRoute,
}

const BarsLazyRouteWithChildren = BarsLazyRoute._addFileChildren(
  BarsLazyRouteChildren,
)

interface ChartsLazyRouteChildren {
  ChartsCircle1LazyRoute: typeof ChartsCircle1LazyRoute
  ChartsCircle2LazyRoute: typeof ChartsCircle2LazyRoute
  ChartsCircle3LazyRoute: typeof ChartsCircle3LazyRoute
  ChartsCircle4LazyRoute: typeof ChartsCircle4LazyRoute
  ChartsCircle5LazyRoute: typeof ChartsCircle5LazyRoute
  ChartsCircle6LazyRoute: typeof ChartsCircle6LazyRoute
}

const ChartsLazyRouteChildren: ChartsLazyRouteChildren = {
  ChartsCircle1LazyRoute: ChartsCircle1LazyRoute,
  ChartsCircle2LazyRoute: ChartsCircle2LazyRoute,
  ChartsCircle3LazyRoute: ChartsCircle3LazyRoute,
  ChartsCircle4LazyRoute: ChartsCircle4LazyRoute,
  ChartsCircle5LazyRoute: ChartsCircle5LazyRoute,
  ChartsCircle6LazyRoute: ChartsCircle6LazyRoute,
}

const ChartsLazyRouteWithChildren = ChartsLazyRoute._addFileChildren(
  ChartsLazyRouteChildren,
)

interface GraphLazyRouteChildren {
  GraphGraph1LazyRoute: typeof GraphGraph1LazyRoute
  GraphGraph2LazyRoute: typeof GraphGraph2LazyRoute
}

const GraphLazyRouteChildren: GraphLazyRouteChildren = {
  GraphGraph1LazyRoute: GraphGraph1LazyRoute,
  GraphGraph2LazyRoute: GraphGraph2LazyRoute,
}

const GraphLazyRouteWithChildren = GraphLazyRoute._addFileChildren(
  GraphLazyRouteChildren,
)

interface KpistatsLazyRouteChildren {
  KpistatsKpistat1LazyRoute: typeof KpistatsKpistat1LazyRoute
  KpistatsKpistat2LazyRoute: typeof KpistatsKpistat2LazyRoute
  KpistatsKpistat3LazyRoute: typeof KpistatsKpistat3LazyRoute
  KpistatsKpistat4LazyRoute: typeof KpistatsKpistat4LazyRoute
}

const KpistatsLazyRouteChildren: KpistatsLazyRouteChildren = {
  KpistatsKpistat1LazyRoute: KpistatsKpistat1LazyRoute,
  KpistatsKpistat2LazyRoute: KpistatsKpistat2LazyRoute,
  KpistatsKpistat3LazyRoute: KpistatsKpistat3LazyRoute,
  KpistatsKpistat4LazyRoute: KpistatsKpistat4LazyRoute,
}

const KpistatsLazyRouteWithChildren = KpistatsLazyRoute._addFileChildren(
  KpistatsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BarsLazyRoute: BarsLazyRouteWithChildren,
  ChartsLazyRoute: ChartsLazyRouteWithChildren,
  GraphLazyRoute: GraphLazyRouteWithChildren,
  KpistatsLazyRoute: KpistatsLazyRouteWithChildren,
  TestLazyRoute: TestLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
