/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TestLazyRouteImport = createFileRoute('/test')()
const TeamsLazyRouteImport = createFileRoute('/teams')()
const PricingComparisonLazyRouteImport = createFileRoute(
  '/pricing-comparison',
)()
const PricingLazyRouteImport = createFileRoute('/pricing')()
const KpistatsLazyRouteImport = createFileRoute('/kpistats')()
const HerosectionLazyRouteImport = createFileRoute('/herosection')()
const GraphLazyRouteImport = createFileRoute('/graph')()
const FooterLazyRouteImport = createFileRoute('/footer')()
const FaqsLazyRouteImport = createFileRoute('/faqs')()
const CookiesLazyRouteImport = createFileRoute('/cookies')()
const ChartsLazyRouteImport = createFileRoute('/charts')()
const BarsLazyRouteImport = createFileRoute('/bars')()
const BannerLazyRouteImport = createFileRoute('/banner')()
const IndexLazyRouteImport = createFileRoute('/')()
const PricingPricingSimplepriceLazyRouteImport = createFileRoute(
  '/pricing/pricing-simpleprice',
)()
const PricingPricingMostpopulartierfilledLazyRouteImport = createFileRoute(
  '/pricing/pricing-mostpopulartierfilled',
)()
const PricingPricingMostpopulartierLazyRouteImport = createFileRoute(
  '/pricing/pricing-mostpopulartier',
)()
const PricingPricingMostpopularhighlightedLazyRouteImport = createFileRoute(
  '/pricing/pricing-mostpopularhighlighted',
)()
const PricingPricingFeaturedtierFilledLazyRouteImport = createFileRoute(
  '/pricing/pricing-featuredtier-filled',
)()
const PricingPricingFeaturedtierLazyRouteImport = createFileRoute(
  '/pricing/pricing-featuredtier',
)()
const PricingPricingBlurredbackgroundLazyRouteImport = createFileRoute(
  '/pricing/pricing-blurredbackground',
)()
const PricingPricingBasepriceLazyRouteImport = createFileRoute(
  '/pricing/pricing-baseprice',
)()
const PricingComparisonPricingComparisonStickyheaderLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-stickyheader')()
const PricingComparisonPricingComparisonMostpopularsoftLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-mostpopularsoft')()
const PricingComparisonPricingComparisonMostpopularLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-mostpopular')()
const PricingComparisonPricingComparisonHighlightedLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-highlighted')()
const PricingComparisonPricingComparisonFeaturefilledLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-featurefilled')()
const PricingComparisonPricingComparisonFeaturedLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-featured')()
const PricingComparisonPricingComparisonBlurredLazyRouteImport =
  createFileRoute('/pricing-comparison/pricing-comparison-blurred')()
const PricingComparisonPricingComparisonBaseLazyRouteImport = createFileRoute(
  '/pricing-comparison/pricing-comparison-base',
)()
const KpistatsKpistat9LazyRouteImport = createFileRoute('/kpistats/kpistat-9')()
const KpistatsKpistat8LazyRouteImport = createFileRoute('/kpistats/kpistat-8')()
const KpistatsKpistat7LazyRouteImport = createFileRoute('/kpistats/kpistat-7')()
const KpistatsKpistat6LazyRouteImport = createFileRoute('/kpistats/kpistat-6')()
const KpistatsKpistat5LazyRouteImport = createFileRoute('/kpistats/kpistat-5')()
const KpistatsKpistat4LazyRouteImport = createFileRoute('/kpistats/kpistat-4')()
const KpistatsKpistat3LazyRouteImport = createFileRoute('/kpistats/kpistat-3')()
const KpistatsKpistat2LazyRouteImport = createFileRoute('/kpistats/kpistat-2')()
const KpistatsKpistat1LazyRouteImport = createFileRoute('/kpistats/kpistat-1')()
const HerosectionHerosectionSkewedLazyRouteImport = createFileRoute(
  '/herosection/herosection-skewed',
)()
const HerosectionHerosectionScreenshotLazyRouteImport = createFileRoute(
  '/herosection/herosection-screenshot',
)()
const HerosectionHerosectionCenterednavbarLazyRouteImport = createFileRoute(
  '/herosection/herosection-centerednavbar',
)()
const HerosectionHerosectionBasicLazyRouteImport = createFileRoute(
  '/herosection/herosection-basic',
)()
const GraphGraph2LazyRouteImport = createFileRoute('/graph/graph-2')()
const GraphGraph1LazyRouteImport = createFileRoute('/graph/graph-1')()
const FootersFooterThemeLazyRouteImport = createFileRoute(
  '/footers/footer-theme',
)()
const FootersFooterSocialLinkLazyRouteImport = createFileRoute(
  '/footers/footer-socialLink',
)()
const FootersFooterNewsletterLazyRouteImport = createFileRoute(
  '/footers/footer-newsletter',
)()
const FootersFooterColumnLazyRouteImport = createFileRoute(
  '/footers/footer-column',
)()
const FaqsTwocolumnFaqsLazyRouteImport = createFileRoute(
  '/faqs/twocolumn-faqs',
)()
const FaqsFaqsDividerLazyRouteImport = createFileRoute('/faqs/faqs-divider')()
const FaqsCenteredFaqsLazyRouteImport = createFileRoute('/faqs/centered-faqs')()
const FaqsBasicFaqsLazyRouteImport = createFileRoute('/faqs/basic-faqs')()
const CookiesCookiesVerticalbuttonsLazyRouteImport = createFileRoute(
  '/cookies/cookies-verticalbuttons',
)()
const CookiesCookiesFullwidthLazyRouteImport = createFileRoute(
  '/cookies/cookies-fullwidth',
)()
const CookiesCookiesFloatingbottomLazyRouteImport = createFileRoute(
  '/cookies/cookies-floatingbottom',
)()
const CookiesCookiesBrandcolorsLazyRouteImport = createFileRoute(
  '/cookies/cookies-brandcolors',
)()
const CookiesCookiesBottomfixedLazyRouteImport = createFileRoute(
  '/cookies/cookies-bottomfixed',
)()
const CookiesCookiesBottomcenterLazyRouteImport = createFileRoute(
  '/cookies/cookies-bottomcenter',
)()
const CookiesCookiesBasicLazyRouteImport = createFileRoute(
  '/cookies/cookies-basic',
)()
const CookiesCookiesAnimatedLazyRouteImport = createFileRoute(
  '/cookies/cookies-animated',
)()
const ChartsCircle6LazyRouteImport = createFileRoute('/charts/circle-6')()
const ChartsCircle5LazyRouteImport = createFileRoute('/charts/circle-5')()
const ChartsCircle4LazyRouteImport = createFileRoute('/charts/circle-4')()
const ChartsCircle3LazyRouteImport = createFileRoute('/charts/circle-3')()
const ChartsCircle2LazyRouteImport = createFileRoute('/charts/circle-2')()
const ChartsCircle1LazyRouteImport = createFileRoute('/charts/circle-1')()
const BarsBars4LazyRouteImport = createFileRoute('/bars/bars-4')()
const BarsBars3LazyRouteImport = createFileRoute('/bars/bars-3')()
const BarsBars2LazyRouteImport = createFileRoute('/bars/bars-2')()
const BarsBars1LazyRouteImport = createFileRoute('/bars/bars-1')()
const BannersBannerInvertedLazyRouteImport = createFileRoute(
  '/banners/banner-inverted',
)()
const BannersBannerGradientLazyRouteImport = createFileRoute(
  '/banners/banner-gradient',
)()
const BannersBannerFloatbottomcenterLazyRouteImport = createFileRoute(
  '/banners/banner-floatbottomcenter',
)()
const BannersBannerFloatbottomLazyRouteImport = createFileRoute(
  '/banners/banner-floatbottom',
)()
const BannersBannerFloatLazyRouteImport = createFileRoute(
  '/banners/banner-float',
)()
const BannersBannerBrandcolorsLazyRouteImport = createFileRoute(
  '/banners/banner-brandcolors',
)()
const BannersBannerBetweenjustifiedLazyRouteImport = createFileRoute(
  '/banners/banner-betweenjustified',
)()
const BannersBannerBasicLazyRouteImport = createFileRoute(
  '/banners/banner-basic',
)()

const TestLazyRoute = TestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))
const TeamsLazyRoute = TeamsLazyRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.lazy').then((d) => d.Route))
const PricingComparisonLazyRoute = PricingComparisonLazyRouteImport.update({
  id: '/pricing-comparison',
  path: '/pricing-comparison',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/pricing-comparison.lazy').then((d) => d.Route),
)
const PricingLazyRoute = PricingLazyRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const KpistatsLazyRoute = KpistatsLazyRouteImport.update({
  id: '/kpistats',
  path: '/kpistats',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kpistats.lazy').then((d) => d.Route))
const HerosectionLazyRoute = HerosectionLazyRouteImport.update({
  id: '/herosection',
  path: '/herosection',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/herosection.lazy').then((d) => d.Route))
const GraphLazyRoute = GraphLazyRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/graph.lazy').then((d) => d.Route))
const FooterLazyRoute = FooterLazyRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/footer.lazy').then((d) => d.Route))
const FaqsLazyRoute = FaqsLazyRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faqs.lazy').then((d) => d.Route))
const CookiesLazyRoute = CookiesLazyRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const ChartsLazyRoute = ChartsLazyRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts.lazy').then((d) => d.Route))
const BarsLazyRoute = BarsLazyRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bars.lazy').then((d) => d.Route))
const BannerLazyRoute = BannerLazyRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/banner.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PricingPricingSimplepriceLazyRoute =
  PricingPricingSimplepriceLazyRouteImport.update({
    id: '/pricing-simpleprice',
    path: '/pricing-simpleprice',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-simpleprice.lazy').then((d) => d.Route),
  )
const PricingPricingMostpopulartierfilledLazyRoute =
  PricingPricingMostpopulartierfilledLazyRouteImport.update({
    id: '/pricing-mostpopulartierfilled',
    path: '/pricing-mostpopulartierfilled',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-mostpopulartierfilled.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingPricingMostpopulartierLazyRoute =
  PricingPricingMostpopulartierLazyRouteImport.update({
    id: '/pricing-mostpopulartier',
    path: '/pricing-mostpopulartier',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-mostpopulartier.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingPricingMostpopularhighlightedLazyRoute =
  PricingPricingMostpopularhighlightedLazyRouteImport.update({
    id: '/pricing-mostpopularhighlighted',
    path: '/pricing-mostpopularhighlighted',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-mostpopularhighlighted.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingPricingFeaturedtierFilledLazyRoute =
  PricingPricingFeaturedtierFilledLazyRouteImport.update({
    id: '/pricing-featuredtier-filled',
    path: '/pricing-featuredtier-filled',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-featuredtier-filled.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingPricingFeaturedtierLazyRoute =
  PricingPricingFeaturedtierLazyRouteImport.update({
    id: '/pricing-featuredtier',
    path: '/pricing-featuredtier',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-featuredtier.lazy').then((d) => d.Route),
  )
const PricingPricingBlurredbackgroundLazyRoute =
  PricingPricingBlurredbackgroundLazyRouteImport.update({
    id: '/pricing-blurredbackground',
    path: '/pricing-blurredbackground',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-blurredbackground.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingPricingBasepriceLazyRoute =
  PricingPricingBasepriceLazyRouteImport.update({
    id: '/pricing-baseprice',
    path: '/pricing-baseprice',
    getParentRoute: () => PricingLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing/pricing-baseprice.lazy').then((d) => d.Route),
  )
const PricingComparisonPricingComparisonStickyheaderLazyRoute =
  PricingComparisonPricingComparisonStickyheaderLazyRouteImport.update({
    id: '/pricing-comparison-stickyheader',
    path: '/pricing-comparison-stickyheader',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/pricing-comparison/pricing-comparison-stickyheader.lazy'
    ).then((d) => d.Route),
  )
const PricingComparisonPricingComparisonMostpopularsoftLazyRoute =
  PricingComparisonPricingComparisonMostpopularsoftLazyRouteImport.update({
    id: '/pricing-comparison-mostpopularsoft',
    path: '/pricing-comparison-mostpopularsoft',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/pricing-comparison/pricing-comparison-mostpopularsoft.lazy'
    ).then((d) => d.Route),
  )
const PricingComparisonPricingComparisonMostpopularLazyRoute =
  PricingComparisonPricingComparisonMostpopularLazyRouteImport.update({
    id: '/pricing-comparison-mostpopular',
    path: '/pricing-comparison-mostpopular',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/pricing-comparison/pricing-comparison-mostpopular.lazy'
    ).then((d) => d.Route),
  )
const PricingComparisonPricingComparisonHighlightedLazyRoute =
  PricingComparisonPricingComparisonHighlightedLazyRouteImport.update({
    id: '/pricing-comparison-highlighted',
    path: '/pricing-comparison-highlighted',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/pricing-comparison/pricing-comparison-highlighted.lazy'
    ).then((d) => d.Route),
  )
const PricingComparisonPricingComparisonFeaturefilledLazyRoute =
  PricingComparisonPricingComparisonFeaturefilledLazyRouteImport.update({
    id: '/pricing-comparison-featurefilled',
    path: '/pricing-comparison-featurefilled',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/pricing-comparison/pricing-comparison-featurefilled.lazy'
    ).then((d) => d.Route),
  )
const PricingComparisonPricingComparisonFeaturedLazyRoute =
  PricingComparisonPricingComparisonFeaturedLazyRouteImport.update({
    id: '/pricing-comparison-featured',
    path: '/pricing-comparison-featured',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing-comparison/pricing-comparison-featured.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingComparisonPricingComparisonBlurredLazyRoute =
  PricingComparisonPricingComparisonBlurredLazyRouteImport.update({
    id: '/pricing-comparison-blurred',
    path: '/pricing-comparison-blurred',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing-comparison/pricing-comparison-blurred.lazy').then(
      (d) => d.Route,
    ),
  )
const PricingComparisonPricingComparisonBaseLazyRoute =
  PricingComparisonPricingComparisonBaseLazyRouteImport.update({
    id: '/pricing-comparison-base',
    path: '/pricing-comparison-base',
    getParentRoute: () => PricingComparisonLazyRoute,
  } as any).lazy(() =>
    import('./routes/pricing-comparison/pricing-comparison-base.lazy').then(
      (d) => d.Route,
    ),
  )
const KpistatsKpistat9LazyRoute = KpistatsKpistat9LazyRouteImport.update({
  id: '/kpistat-9',
  path: '/kpistat-9',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-9.lazy').then((d) => d.Route),
)
const KpistatsKpistat8LazyRoute = KpistatsKpistat8LazyRouteImport.update({
  id: '/kpistat-8',
  path: '/kpistat-8',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-8.lazy').then((d) => d.Route),
)
const KpistatsKpistat7LazyRoute = KpistatsKpistat7LazyRouteImport.update({
  id: '/kpistat-7',
  path: '/kpistat-7',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-7.lazy').then((d) => d.Route),
)
const KpistatsKpistat6LazyRoute = KpistatsKpistat6LazyRouteImport.update({
  id: '/kpistat-6',
  path: '/kpistat-6',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-6.lazy').then((d) => d.Route),
)
const KpistatsKpistat5LazyRoute = KpistatsKpistat5LazyRouteImport.update({
  id: '/kpistat-5',
  path: '/kpistat-5',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-5.lazy').then((d) => d.Route),
)
const KpistatsKpistat4LazyRoute = KpistatsKpistat4LazyRouteImport.update({
  id: '/kpistat-4',
  path: '/kpistat-4',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-4.lazy').then((d) => d.Route),
)
const KpistatsKpistat3LazyRoute = KpistatsKpistat3LazyRouteImport.update({
  id: '/kpistat-3',
  path: '/kpistat-3',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-3.lazy').then((d) => d.Route),
)
const KpistatsKpistat2LazyRoute = KpistatsKpistat2LazyRouteImport.update({
  id: '/kpistat-2',
  path: '/kpistat-2',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-2.lazy').then((d) => d.Route),
)
const KpistatsKpistat1LazyRoute = KpistatsKpistat1LazyRouteImport.update({
  id: '/kpistat-1',
  path: '/kpistat-1',
  getParentRoute: () => KpistatsLazyRoute,
} as any).lazy(() =>
  import('./routes/kpistats/kpistat-1.lazy').then((d) => d.Route),
)
const HerosectionHerosectionSkewedLazyRoute =
  HerosectionHerosectionSkewedLazyRouteImport.update({
    id: '/herosection-skewed',
    path: '/herosection-skewed',
    getParentRoute: () => HerosectionLazyRoute,
  } as any).lazy(() =>
    import('./routes/herosection/herosection-skewed.lazy').then((d) => d.Route),
  )
const HerosectionHerosectionScreenshotLazyRoute =
  HerosectionHerosectionScreenshotLazyRouteImport.update({
    id: '/herosection-screenshot',
    path: '/herosection-screenshot',
    getParentRoute: () => HerosectionLazyRoute,
  } as any).lazy(() =>
    import('./routes/herosection/herosection-screenshot.lazy').then(
      (d) => d.Route,
    ),
  )
const HerosectionHerosectionCenterednavbarLazyRoute =
  HerosectionHerosectionCenterednavbarLazyRouteImport.update({
    id: '/herosection-centerednavbar',
    path: '/herosection-centerednavbar',
    getParentRoute: () => HerosectionLazyRoute,
  } as any).lazy(() =>
    import('./routes/herosection/herosection-centerednavbar.lazy').then(
      (d) => d.Route,
    ),
  )
const HerosectionHerosectionBasicLazyRoute =
  HerosectionHerosectionBasicLazyRouteImport.update({
    id: '/herosection-basic',
    path: '/herosection-basic',
    getParentRoute: () => HerosectionLazyRoute,
  } as any).lazy(() =>
    import('./routes/herosection/herosection-basic.lazy').then((d) => d.Route),
  )
const GraphGraph2LazyRoute = GraphGraph2LazyRouteImport.update({
  id: '/graph-2',
  path: '/graph-2',
  getParentRoute: () => GraphLazyRoute,
} as any).lazy(() => import('./routes/graph/graph-2.lazy').then((d) => d.Route))
const GraphGraph1LazyRoute = GraphGraph1LazyRouteImport.update({
  id: '/graph-1',
  path: '/graph-1',
  getParentRoute: () => GraphLazyRoute,
} as any).lazy(() => import('./routes/graph/graph-1.lazy').then((d) => d.Route))
const FootersFooterThemeLazyRoute = FootersFooterThemeLazyRouteImport.update({
  id: '/footers/footer-theme',
  path: '/footers/footer-theme',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/footers/footer-theme.lazy').then((d) => d.Route),
)
const FootersFooterSocialLinkLazyRoute =
  FootersFooterSocialLinkLazyRouteImport.update({
    id: '/footers/footer-socialLink',
    path: '/footers/footer-socialLink',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/footers/footer-socialLink.lazy').then((d) => d.Route),
  )
const FootersFooterNewsletterLazyRoute =
  FootersFooterNewsletterLazyRouteImport.update({
    id: '/footers/footer-newsletter',
    path: '/footers/footer-newsletter',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/footers/footer-newsletter.lazy').then((d) => d.Route),
  )
const FootersFooterColumnLazyRoute = FootersFooterColumnLazyRouteImport.update({
  id: '/footers/footer-column',
  path: '/footers/footer-column',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/footers/footer-column.lazy').then((d) => d.Route),
)
const FaqsTwocolumnFaqsLazyRoute = FaqsTwocolumnFaqsLazyRouteImport.update({
  id: '/twocolumn-faqs',
  path: '/twocolumn-faqs',
  getParentRoute: () => FaqsLazyRoute,
} as any).lazy(() =>
  import('./routes/faqs/twocolumn-faqs.lazy').then((d) => d.Route),
)
const FaqsFaqsDividerLazyRoute = FaqsFaqsDividerLazyRouteImport.update({
  id: '/faqs-divider',
  path: '/faqs-divider',
  getParentRoute: () => FaqsLazyRoute,
} as any).lazy(() =>
  import('./routes/faqs/faqs-divider.lazy').then((d) => d.Route),
)
const FaqsCenteredFaqsLazyRoute = FaqsCenteredFaqsLazyRouteImport.update({
  id: '/centered-faqs',
  path: '/centered-faqs',
  getParentRoute: () => FaqsLazyRoute,
} as any).lazy(() =>
  import('./routes/faqs/centered-faqs.lazy').then((d) => d.Route),
)
const FaqsBasicFaqsLazyRoute = FaqsBasicFaqsLazyRouteImport.update({
  id: '/basic-faqs',
  path: '/basic-faqs',
  getParentRoute: () => FaqsLazyRoute,
} as any).lazy(() =>
  import('./routes/faqs/basic-faqs.lazy').then((d) => d.Route),
)
const CookiesCookiesVerticalbuttonsLazyRoute =
  CookiesCookiesVerticalbuttonsLazyRouteImport.update({
    id: '/cookies-verticalbuttons',
    path: '/cookies-verticalbuttons',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-verticalbuttons.lazy').then(
      (d) => d.Route,
    ),
  )
const CookiesCookiesFullwidthLazyRoute =
  CookiesCookiesFullwidthLazyRouteImport.update({
    id: '/cookies-fullwidth',
    path: '/cookies-fullwidth',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-fullwidth.lazy').then((d) => d.Route),
  )
const CookiesCookiesFloatingbottomLazyRoute =
  CookiesCookiesFloatingbottomLazyRouteImport.update({
    id: '/cookies-floatingbottom',
    path: '/cookies-floatingbottom',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-floatingbottom.lazy').then((d) => d.Route),
  )
const CookiesCookiesBrandcolorsLazyRoute =
  CookiesCookiesBrandcolorsLazyRouteImport.update({
    id: '/cookies-brandcolors',
    path: '/cookies-brandcolors',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-brandcolors.lazy').then((d) => d.Route),
  )
const CookiesCookiesBottomfixedLazyRoute =
  CookiesCookiesBottomfixedLazyRouteImport.update({
    id: '/cookies-bottomfixed',
    path: '/cookies-bottomfixed',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-bottomfixed.lazy').then((d) => d.Route),
  )
const CookiesCookiesBottomcenterLazyRoute =
  CookiesCookiesBottomcenterLazyRouteImport.update({
    id: '/cookies-bottomcenter',
    path: '/cookies-bottomcenter',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-bottomcenter.lazy').then((d) => d.Route),
  )
const CookiesCookiesBasicLazyRoute = CookiesCookiesBasicLazyRouteImport.update({
  id: '/cookies-basic',
  path: '/cookies-basic',
  getParentRoute: () => CookiesLazyRoute,
} as any).lazy(() =>
  import('./routes/cookies/cookies-basic.lazy').then((d) => d.Route),
)
const CookiesCookiesAnimatedLazyRoute =
  CookiesCookiesAnimatedLazyRouteImport.update({
    id: '/cookies-animated',
    path: '/cookies-animated',
    getParentRoute: () => CookiesLazyRoute,
  } as any).lazy(() =>
    import('./routes/cookies/cookies-animated.lazy').then((d) => d.Route),
  )
const ChartsCircle6LazyRoute = ChartsCircle6LazyRouteImport.update({
  id: '/circle-6',
  path: '/circle-6',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-6.lazy').then((d) => d.Route),
)
const ChartsCircle5LazyRoute = ChartsCircle5LazyRouteImport.update({
  id: '/circle-5',
  path: '/circle-5',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-5.lazy').then((d) => d.Route),
)
const ChartsCircle4LazyRoute = ChartsCircle4LazyRouteImport.update({
  id: '/circle-4',
  path: '/circle-4',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-4.lazy').then((d) => d.Route),
)
const ChartsCircle3LazyRoute = ChartsCircle3LazyRouteImport.update({
  id: '/circle-3',
  path: '/circle-3',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-3.lazy').then((d) => d.Route),
)
const ChartsCircle2LazyRoute = ChartsCircle2LazyRouteImport.update({
  id: '/circle-2',
  path: '/circle-2',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-2.lazy').then((d) => d.Route),
)
const ChartsCircle1LazyRoute = ChartsCircle1LazyRouteImport.update({
  id: '/circle-1',
  path: '/circle-1',
  getParentRoute: () => ChartsLazyRoute,
} as any).lazy(() =>
  import('./routes/charts/circle-1.lazy').then((d) => d.Route),
)
const BarsBars4LazyRoute = BarsBars4LazyRouteImport.update({
  id: '/bars-4',
  path: '/bars-4',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-4.lazy').then((d) => d.Route))
const BarsBars3LazyRoute = BarsBars3LazyRouteImport.update({
  id: '/bars-3',
  path: '/bars-3',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-3.lazy').then((d) => d.Route))
const BarsBars2LazyRoute = BarsBars2LazyRouteImport.update({
  id: '/bars-2',
  path: '/bars-2',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-2.lazy').then((d) => d.Route))
const BarsBars1LazyRoute = BarsBars1LazyRouteImport.update({
  id: '/bars-1',
  path: '/bars-1',
  getParentRoute: () => BarsLazyRoute,
} as any).lazy(() => import('./routes/bars/bars-1.lazy').then((d) => d.Route))
const BannersBannerInvertedLazyRoute =
  BannersBannerInvertedLazyRouteImport.update({
    id: '/banners/banner-inverted',
    path: '/banners/banner-inverted',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-inverted.lazy').then((d) => d.Route),
  )
const BannersBannerGradientLazyRoute =
  BannersBannerGradientLazyRouteImport.update({
    id: '/banners/banner-gradient',
    path: '/banners/banner-gradient',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-gradient.lazy').then((d) => d.Route),
  )
const BannersBannerFloatbottomcenterLazyRoute =
  BannersBannerFloatbottomcenterLazyRouteImport.update({
    id: '/banners/banner-floatbottomcenter',
    path: '/banners/banner-floatbottomcenter',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-floatbottomcenter.lazy').then(
      (d) => d.Route,
    ),
  )
const BannersBannerFloatbottomLazyRoute =
  BannersBannerFloatbottomLazyRouteImport.update({
    id: '/banners/banner-floatbottom',
    path: '/banners/banner-floatbottom',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-floatbottom.lazy').then((d) => d.Route),
  )
const BannersBannerFloatLazyRoute = BannersBannerFloatLazyRouteImport.update({
  id: '/banners/banner-float',
  path: '/banners/banner-float',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/banners/banner-float.lazy').then((d) => d.Route),
)
const BannersBannerBrandcolorsLazyRoute =
  BannersBannerBrandcolorsLazyRouteImport.update({
    id: '/banners/banner-brandcolors',
    path: '/banners/banner-brandcolors',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-brandcolors.lazy').then((d) => d.Route),
  )
const BannersBannerBetweenjustifiedLazyRoute =
  BannersBannerBetweenjustifiedLazyRouteImport.update({
    id: '/banners/banner-betweenjustified',
    path: '/banners/banner-betweenjustified',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/banners/banner-betweenjustified.lazy').then(
      (d) => d.Route,
    ),
  )
const BannersBannerBasicLazyRoute = BannersBannerBasicLazyRouteImport.update({
  id: '/banners/banner-basic',
  path: '/banners/banner-basic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/banners/banner-basic.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/banner': typeof BannerLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/cookies': typeof CookiesLazyRouteWithChildren
  '/faqs': typeof FaqsLazyRouteWithChildren
  '/footer': typeof FooterLazyRoute
  '/graph': typeof GraphLazyRouteWithChildren
  '/herosection': typeof HerosectionLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/pricing': typeof PricingLazyRouteWithChildren
  '/pricing-comparison': typeof PricingComparisonLazyRouteWithChildren
  '/teams': typeof TeamsLazyRoute
  '/test': typeof TestLazyRoute
  '/banners/banner-basic': typeof BannersBannerBasicLazyRoute
  '/banners/banner-betweenjustified': typeof BannersBannerBetweenjustifiedLazyRoute
  '/banners/banner-brandcolors': typeof BannersBannerBrandcolorsLazyRoute
  '/banners/banner-float': typeof BannersBannerFloatLazyRoute
  '/banners/banner-floatbottom': typeof BannersBannerFloatbottomLazyRoute
  '/banners/banner-floatbottomcenter': typeof BannersBannerFloatbottomcenterLazyRoute
  '/banners/banner-gradient': typeof BannersBannerGradientLazyRoute
  '/banners/banner-inverted': typeof BannersBannerInvertedLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/cookies/cookies-animated': typeof CookiesCookiesAnimatedLazyRoute
  '/cookies/cookies-basic': typeof CookiesCookiesBasicLazyRoute
  '/cookies/cookies-bottomcenter': typeof CookiesCookiesBottomcenterLazyRoute
  '/cookies/cookies-bottomfixed': typeof CookiesCookiesBottomfixedLazyRoute
  '/cookies/cookies-brandcolors': typeof CookiesCookiesBrandcolorsLazyRoute
  '/cookies/cookies-floatingbottom': typeof CookiesCookiesFloatingbottomLazyRoute
  '/cookies/cookies-fullwidth': typeof CookiesCookiesFullwidthLazyRoute
  '/cookies/cookies-verticalbuttons': typeof CookiesCookiesVerticalbuttonsLazyRoute
  '/faqs/basic-faqs': typeof FaqsBasicFaqsLazyRoute
  '/faqs/centered-faqs': typeof FaqsCenteredFaqsLazyRoute
  '/faqs/faqs-divider': typeof FaqsFaqsDividerLazyRoute
  '/faqs/twocolumn-faqs': typeof FaqsTwocolumnFaqsLazyRoute
  '/footers/footer-column': typeof FootersFooterColumnLazyRoute
  '/footers/footer-newsletter': typeof FootersFooterNewsletterLazyRoute
  '/footers/footer-socialLink': typeof FootersFooterSocialLinkLazyRoute
  '/footers/footer-theme': typeof FootersFooterThemeLazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/herosection/herosection-basic': typeof HerosectionHerosectionBasicLazyRoute
  '/herosection/herosection-centerednavbar': typeof HerosectionHerosectionCenterednavbarLazyRoute
  '/herosection/herosection-screenshot': typeof HerosectionHerosectionScreenshotLazyRoute
  '/herosection/herosection-skewed': typeof HerosectionHerosectionSkewedLazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
  '/kpistats/kpistat-5': typeof KpistatsKpistat5LazyRoute
  '/kpistats/kpistat-6': typeof KpistatsKpistat6LazyRoute
  '/kpistats/kpistat-7': typeof KpistatsKpistat7LazyRoute
  '/kpistats/kpistat-8': typeof KpistatsKpistat8LazyRoute
  '/kpistats/kpistat-9': typeof KpistatsKpistat9LazyRoute
  '/pricing-comparison/pricing-comparison-base': typeof PricingComparisonPricingComparisonBaseLazyRoute
  '/pricing-comparison/pricing-comparison-blurred': typeof PricingComparisonPricingComparisonBlurredLazyRoute
  '/pricing-comparison/pricing-comparison-featured': typeof PricingComparisonPricingComparisonFeaturedLazyRoute
  '/pricing-comparison/pricing-comparison-featurefilled': typeof PricingComparisonPricingComparisonFeaturefilledLazyRoute
  '/pricing-comparison/pricing-comparison-highlighted': typeof PricingComparisonPricingComparisonHighlightedLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopular': typeof PricingComparisonPricingComparisonMostpopularLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopularsoft': typeof PricingComparisonPricingComparisonMostpopularsoftLazyRoute
  '/pricing-comparison/pricing-comparison-stickyheader': typeof PricingComparisonPricingComparisonStickyheaderLazyRoute
  '/pricing/pricing-baseprice': typeof PricingPricingBasepriceLazyRoute
  '/pricing/pricing-blurredbackground': typeof PricingPricingBlurredbackgroundLazyRoute
  '/pricing/pricing-featuredtier': typeof PricingPricingFeaturedtierLazyRoute
  '/pricing/pricing-featuredtier-filled': typeof PricingPricingFeaturedtierFilledLazyRoute
  '/pricing/pricing-mostpopularhighlighted': typeof PricingPricingMostpopularhighlightedLazyRoute
  '/pricing/pricing-mostpopulartier': typeof PricingPricingMostpopulartierLazyRoute
  '/pricing/pricing-mostpopulartierfilled': typeof PricingPricingMostpopulartierfilledLazyRoute
  '/pricing/pricing-simpleprice': typeof PricingPricingSimplepriceLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/banner': typeof BannerLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/cookies': typeof CookiesLazyRouteWithChildren
  '/faqs': typeof FaqsLazyRouteWithChildren
  '/footer': typeof FooterLazyRoute
  '/graph': typeof GraphLazyRouteWithChildren
  '/herosection': typeof HerosectionLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/pricing': typeof PricingLazyRouteWithChildren
  '/pricing-comparison': typeof PricingComparisonLazyRouteWithChildren
  '/teams': typeof TeamsLazyRoute
  '/test': typeof TestLazyRoute
  '/banners/banner-basic': typeof BannersBannerBasicLazyRoute
  '/banners/banner-betweenjustified': typeof BannersBannerBetweenjustifiedLazyRoute
  '/banners/banner-brandcolors': typeof BannersBannerBrandcolorsLazyRoute
  '/banners/banner-float': typeof BannersBannerFloatLazyRoute
  '/banners/banner-floatbottom': typeof BannersBannerFloatbottomLazyRoute
  '/banners/banner-floatbottomcenter': typeof BannersBannerFloatbottomcenterLazyRoute
  '/banners/banner-gradient': typeof BannersBannerGradientLazyRoute
  '/banners/banner-inverted': typeof BannersBannerInvertedLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/cookies/cookies-animated': typeof CookiesCookiesAnimatedLazyRoute
  '/cookies/cookies-basic': typeof CookiesCookiesBasicLazyRoute
  '/cookies/cookies-bottomcenter': typeof CookiesCookiesBottomcenterLazyRoute
  '/cookies/cookies-bottomfixed': typeof CookiesCookiesBottomfixedLazyRoute
  '/cookies/cookies-brandcolors': typeof CookiesCookiesBrandcolorsLazyRoute
  '/cookies/cookies-floatingbottom': typeof CookiesCookiesFloatingbottomLazyRoute
  '/cookies/cookies-fullwidth': typeof CookiesCookiesFullwidthLazyRoute
  '/cookies/cookies-verticalbuttons': typeof CookiesCookiesVerticalbuttonsLazyRoute
  '/faqs/basic-faqs': typeof FaqsBasicFaqsLazyRoute
  '/faqs/centered-faqs': typeof FaqsCenteredFaqsLazyRoute
  '/faqs/faqs-divider': typeof FaqsFaqsDividerLazyRoute
  '/faqs/twocolumn-faqs': typeof FaqsTwocolumnFaqsLazyRoute
  '/footers/footer-column': typeof FootersFooterColumnLazyRoute
  '/footers/footer-newsletter': typeof FootersFooterNewsletterLazyRoute
  '/footers/footer-socialLink': typeof FootersFooterSocialLinkLazyRoute
  '/footers/footer-theme': typeof FootersFooterThemeLazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/herosection/herosection-basic': typeof HerosectionHerosectionBasicLazyRoute
  '/herosection/herosection-centerednavbar': typeof HerosectionHerosectionCenterednavbarLazyRoute
  '/herosection/herosection-screenshot': typeof HerosectionHerosectionScreenshotLazyRoute
  '/herosection/herosection-skewed': typeof HerosectionHerosectionSkewedLazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
  '/kpistats/kpistat-5': typeof KpistatsKpistat5LazyRoute
  '/kpistats/kpistat-6': typeof KpistatsKpistat6LazyRoute
  '/kpistats/kpistat-7': typeof KpistatsKpistat7LazyRoute
  '/kpistats/kpistat-8': typeof KpistatsKpistat8LazyRoute
  '/kpistats/kpistat-9': typeof KpistatsKpistat9LazyRoute
  '/pricing-comparison/pricing-comparison-base': typeof PricingComparisonPricingComparisonBaseLazyRoute
  '/pricing-comparison/pricing-comparison-blurred': typeof PricingComparisonPricingComparisonBlurredLazyRoute
  '/pricing-comparison/pricing-comparison-featured': typeof PricingComparisonPricingComparisonFeaturedLazyRoute
  '/pricing-comparison/pricing-comparison-featurefilled': typeof PricingComparisonPricingComparisonFeaturefilledLazyRoute
  '/pricing-comparison/pricing-comparison-highlighted': typeof PricingComparisonPricingComparisonHighlightedLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopular': typeof PricingComparisonPricingComparisonMostpopularLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopularsoft': typeof PricingComparisonPricingComparisonMostpopularsoftLazyRoute
  '/pricing-comparison/pricing-comparison-stickyheader': typeof PricingComparisonPricingComparisonStickyheaderLazyRoute
  '/pricing/pricing-baseprice': typeof PricingPricingBasepriceLazyRoute
  '/pricing/pricing-blurredbackground': typeof PricingPricingBlurredbackgroundLazyRoute
  '/pricing/pricing-featuredtier': typeof PricingPricingFeaturedtierLazyRoute
  '/pricing/pricing-featuredtier-filled': typeof PricingPricingFeaturedtierFilledLazyRoute
  '/pricing/pricing-mostpopularhighlighted': typeof PricingPricingMostpopularhighlightedLazyRoute
  '/pricing/pricing-mostpopulartier': typeof PricingPricingMostpopulartierLazyRoute
  '/pricing/pricing-mostpopulartierfilled': typeof PricingPricingMostpopulartierfilledLazyRoute
  '/pricing/pricing-simpleprice': typeof PricingPricingSimplepriceLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/banner': typeof BannerLazyRoute
  '/bars': typeof BarsLazyRouteWithChildren
  '/charts': typeof ChartsLazyRouteWithChildren
  '/cookies': typeof CookiesLazyRouteWithChildren
  '/faqs': typeof FaqsLazyRouteWithChildren
  '/footer': typeof FooterLazyRoute
  '/graph': typeof GraphLazyRouteWithChildren
  '/herosection': typeof HerosectionLazyRouteWithChildren
  '/kpistats': typeof KpistatsLazyRouteWithChildren
  '/pricing': typeof PricingLazyRouteWithChildren
  '/pricing-comparison': typeof PricingComparisonLazyRouteWithChildren
  '/teams': typeof TeamsLazyRoute
  '/test': typeof TestLazyRoute
  '/banners/banner-basic': typeof BannersBannerBasicLazyRoute
  '/banners/banner-betweenjustified': typeof BannersBannerBetweenjustifiedLazyRoute
  '/banners/banner-brandcolors': typeof BannersBannerBrandcolorsLazyRoute
  '/banners/banner-float': typeof BannersBannerFloatLazyRoute
  '/banners/banner-floatbottom': typeof BannersBannerFloatbottomLazyRoute
  '/banners/banner-floatbottomcenter': typeof BannersBannerFloatbottomcenterLazyRoute
  '/banners/banner-gradient': typeof BannersBannerGradientLazyRoute
  '/banners/banner-inverted': typeof BannersBannerInvertedLazyRoute
  '/bars/bars-1': typeof BarsBars1LazyRoute
  '/bars/bars-2': typeof BarsBars2LazyRoute
  '/bars/bars-3': typeof BarsBars3LazyRoute
  '/bars/bars-4': typeof BarsBars4LazyRoute
  '/charts/circle-1': typeof ChartsCircle1LazyRoute
  '/charts/circle-2': typeof ChartsCircle2LazyRoute
  '/charts/circle-3': typeof ChartsCircle3LazyRoute
  '/charts/circle-4': typeof ChartsCircle4LazyRoute
  '/charts/circle-5': typeof ChartsCircle5LazyRoute
  '/charts/circle-6': typeof ChartsCircle6LazyRoute
  '/cookies/cookies-animated': typeof CookiesCookiesAnimatedLazyRoute
  '/cookies/cookies-basic': typeof CookiesCookiesBasicLazyRoute
  '/cookies/cookies-bottomcenter': typeof CookiesCookiesBottomcenterLazyRoute
  '/cookies/cookies-bottomfixed': typeof CookiesCookiesBottomfixedLazyRoute
  '/cookies/cookies-brandcolors': typeof CookiesCookiesBrandcolorsLazyRoute
  '/cookies/cookies-floatingbottom': typeof CookiesCookiesFloatingbottomLazyRoute
  '/cookies/cookies-fullwidth': typeof CookiesCookiesFullwidthLazyRoute
  '/cookies/cookies-verticalbuttons': typeof CookiesCookiesVerticalbuttonsLazyRoute
  '/faqs/basic-faqs': typeof FaqsBasicFaqsLazyRoute
  '/faqs/centered-faqs': typeof FaqsCenteredFaqsLazyRoute
  '/faqs/faqs-divider': typeof FaqsFaqsDividerLazyRoute
  '/faqs/twocolumn-faqs': typeof FaqsTwocolumnFaqsLazyRoute
  '/footers/footer-column': typeof FootersFooterColumnLazyRoute
  '/footers/footer-newsletter': typeof FootersFooterNewsletterLazyRoute
  '/footers/footer-socialLink': typeof FootersFooterSocialLinkLazyRoute
  '/footers/footer-theme': typeof FootersFooterThemeLazyRoute
  '/graph/graph-1': typeof GraphGraph1LazyRoute
  '/graph/graph-2': typeof GraphGraph2LazyRoute
  '/herosection/herosection-basic': typeof HerosectionHerosectionBasicLazyRoute
  '/herosection/herosection-centerednavbar': typeof HerosectionHerosectionCenterednavbarLazyRoute
  '/herosection/herosection-screenshot': typeof HerosectionHerosectionScreenshotLazyRoute
  '/herosection/herosection-skewed': typeof HerosectionHerosectionSkewedLazyRoute
  '/kpistats/kpistat-1': typeof KpistatsKpistat1LazyRoute
  '/kpistats/kpistat-2': typeof KpistatsKpistat2LazyRoute
  '/kpistats/kpistat-3': typeof KpistatsKpistat3LazyRoute
  '/kpistats/kpistat-4': typeof KpistatsKpistat4LazyRoute
  '/kpistats/kpistat-5': typeof KpistatsKpistat5LazyRoute
  '/kpistats/kpistat-6': typeof KpistatsKpistat6LazyRoute
  '/kpistats/kpistat-7': typeof KpistatsKpistat7LazyRoute
  '/kpistats/kpistat-8': typeof KpistatsKpistat8LazyRoute
  '/kpistats/kpistat-9': typeof KpistatsKpistat9LazyRoute
  '/pricing-comparison/pricing-comparison-base': typeof PricingComparisonPricingComparisonBaseLazyRoute
  '/pricing-comparison/pricing-comparison-blurred': typeof PricingComparisonPricingComparisonBlurredLazyRoute
  '/pricing-comparison/pricing-comparison-featured': typeof PricingComparisonPricingComparisonFeaturedLazyRoute
  '/pricing-comparison/pricing-comparison-featurefilled': typeof PricingComparisonPricingComparisonFeaturefilledLazyRoute
  '/pricing-comparison/pricing-comparison-highlighted': typeof PricingComparisonPricingComparisonHighlightedLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopular': typeof PricingComparisonPricingComparisonMostpopularLazyRoute
  '/pricing-comparison/pricing-comparison-mostpopularsoft': typeof PricingComparisonPricingComparisonMostpopularsoftLazyRoute
  '/pricing-comparison/pricing-comparison-stickyheader': typeof PricingComparisonPricingComparisonStickyheaderLazyRoute
  '/pricing/pricing-baseprice': typeof PricingPricingBasepriceLazyRoute
  '/pricing/pricing-blurredbackground': typeof PricingPricingBlurredbackgroundLazyRoute
  '/pricing/pricing-featuredtier': typeof PricingPricingFeaturedtierLazyRoute
  '/pricing/pricing-featuredtier-filled': typeof PricingPricingFeaturedtierFilledLazyRoute
  '/pricing/pricing-mostpopularhighlighted': typeof PricingPricingMostpopularhighlightedLazyRoute
  '/pricing/pricing-mostpopulartier': typeof PricingPricingMostpopulartierLazyRoute
  '/pricing/pricing-mostpopulartierfilled': typeof PricingPricingMostpopulartierfilledLazyRoute
  '/pricing/pricing-simpleprice': typeof PricingPricingSimplepriceLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banner'
    | '/bars'
    | '/charts'
    | '/cookies'
    | '/faqs'
    | '/footer'
    | '/graph'
    | '/herosection'
    | '/kpistats'
    | '/pricing'
    | '/pricing-comparison'
    | '/teams'
    | '/test'
    | '/banners/banner-basic'
    | '/banners/banner-betweenjustified'
    | '/banners/banner-brandcolors'
    | '/banners/banner-float'
    | '/banners/banner-floatbottom'
    | '/banners/banner-floatbottomcenter'
    | '/banners/banner-gradient'
    | '/banners/banner-inverted'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/cookies/cookies-animated'
    | '/cookies/cookies-basic'
    | '/cookies/cookies-bottomcenter'
    | '/cookies/cookies-bottomfixed'
    | '/cookies/cookies-brandcolors'
    | '/cookies/cookies-floatingbottom'
    | '/cookies/cookies-fullwidth'
    | '/cookies/cookies-verticalbuttons'
    | '/faqs/basic-faqs'
    | '/faqs/centered-faqs'
    | '/faqs/faqs-divider'
    | '/faqs/twocolumn-faqs'
    | '/footers/footer-column'
    | '/footers/footer-newsletter'
    | '/footers/footer-socialLink'
    | '/footers/footer-theme'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/herosection/herosection-basic'
    | '/herosection/herosection-centerednavbar'
    | '/herosection/herosection-screenshot'
    | '/herosection/herosection-skewed'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
    | '/kpistats/kpistat-5'
    | '/kpistats/kpistat-6'
    | '/kpistats/kpistat-7'
    | '/kpistats/kpistat-8'
    | '/kpistats/kpistat-9'
    | '/pricing-comparison/pricing-comparison-base'
    | '/pricing-comparison/pricing-comparison-blurred'
    | '/pricing-comparison/pricing-comparison-featured'
    | '/pricing-comparison/pricing-comparison-featurefilled'
    | '/pricing-comparison/pricing-comparison-highlighted'
    | '/pricing-comparison/pricing-comparison-mostpopular'
    | '/pricing-comparison/pricing-comparison-mostpopularsoft'
    | '/pricing-comparison/pricing-comparison-stickyheader'
    | '/pricing/pricing-baseprice'
    | '/pricing/pricing-blurredbackground'
    | '/pricing/pricing-featuredtier'
    | '/pricing/pricing-featuredtier-filled'
    | '/pricing/pricing-mostpopularhighlighted'
    | '/pricing/pricing-mostpopulartier'
    | '/pricing/pricing-mostpopulartierfilled'
    | '/pricing/pricing-simpleprice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banner'
    | '/bars'
    | '/charts'
    | '/cookies'
    | '/faqs'
    | '/footer'
    | '/graph'
    | '/herosection'
    | '/kpistats'
    | '/pricing'
    | '/pricing-comparison'
    | '/teams'
    | '/test'
    | '/banners/banner-basic'
    | '/banners/banner-betweenjustified'
    | '/banners/banner-brandcolors'
    | '/banners/banner-float'
    | '/banners/banner-floatbottom'
    | '/banners/banner-floatbottomcenter'
    | '/banners/banner-gradient'
    | '/banners/banner-inverted'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/cookies/cookies-animated'
    | '/cookies/cookies-basic'
    | '/cookies/cookies-bottomcenter'
    | '/cookies/cookies-bottomfixed'
    | '/cookies/cookies-brandcolors'
    | '/cookies/cookies-floatingbottom'
    | '/cookies/cookies-fullwidth'
    | '/cookies/cookies-verticalbuttons'
    | '/faqs/basic-faqs'
    | '/faqs/centered-faqs'
    | '/faqs/faqs-divider'
    | '/faqs/twocolumn-faqs'
    | '/footers/footer-column'
    | '/footers/footer-newsletter'
    | '/footers/footer-socialLink'
    | '/footers/footer-theme'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/herosection/herosection-basic'
    | '/herosection/herosection-centerednavbar'
    | '/herosection/herosection-screenshot'
    | '/herosection/herosection-skewed'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
    | '/kpistats/kpistat-5'
    | '/kpistats/kpistat-6'
    | '/kpistats/kpistat-7'
    | '/kpistats/kpistat-8'
    | '/kpistats/kpistat-9'
    | '/pricing-comparison/pricing-comparison-base'
    | '/pricing-comparison/pricing-comparison-blurred'
    | '/pricing-comparison/pricing-comparison-featured'
    | '/pricing-comparison/pricing-comparison-featurefilled'
    | '/pricing-comparison/pricing-comparison-highlighted'
    | '/pricing-comparison/pricing-comparison-mostpopular'
    | '/pricing-comparison/pricing-comparison-mostpopularsoft'
    | '/pricing-comparison/pricing-comparison-stickyheader'
    | '/pricing/pricing-baseprice'
    | '/pricing/pricing-blurredbackground'
    | '/pricing/pricing-featuredtier'
    | '/pricing/pricing-featuredtier-filled'
    | '/pricing/pricing-mostpopularhighlighted'
    | '/pricing/pricing-mostpopulartier'
    | '/pricing/pricing-mostpopulartierfilled'
    | '/pricing/pricing-simpleprice'
  id:
    | '__root__'
    | '/'
    | '/banner'
    | '/bars'
    | '/charts'
    | '/cookies'
    | '/faqs'
    | '/footer'
    | '/graph'
    | '/herosection'
    | '/kpistats'
    | '/pricing'
    | '/pricing-comparison'
    | '/teams'
    | '/test'
    | '/banners/banner-basic'
    | '/banners/banner-betweenjustified'
    | '/banners/banner-brandcolors'
    | '/banners/banner-float'
    | '/banners/banner-floatbottom'
    | '/banners/banner-floatbottomcenter'
    | '/banners/banner-gradient'
    | '/banners/banner-inverted'
    | '/bars/bars-1'
    | '/bars/bars-2'
    | '/bars/bars-3'
    | '/bars/bars-4'
    | '/charts/circle-1'
    | '/charts/circle-2'
    | '/charts/circle-3'
    | '/charts/circle-4'
    | '/charts/circle-5'
    | '/charts/circle-6'
    | '/cookies/cookies-animated'
    | '/cookies/cookies-basic'
    | '/cookies/cookies-bottomcenter'
    | '/cookies/cookies-bottomfixed'
    | '/cookies/cookies-brandcolors'
    | '/cookies/cookies-floatingbottom'
    | '/cookies/cookies-fullwidth'
    | '/cookies/cookies-verticalbuttons'
    | '/faqs/basic-faqs'
    | '/faqs/centered-faqs'
    | '/faqs/faqs-divider'
    | '/faqs/twocolumn-faqs'
    | '/footers/footer-column'
    | '/footers/footer-newsletter'
    | '/footers/footer-socialLink'
    | '/footers/footer-theme'
    | '/graph/graph-1'
    | '/graph/graph-2'
    | '/herosection/herosection-basic'
    | '/herosection/herosection-centerednavbar'
    | '/herosection/herosection-screenshot'
    | '/herosection/herosection-skewed'
    | '/kpistats/kpistat-1'
    | '/kpistats/kpistat-2'
    | '/kpistats/kpistat-3'
    | '/kpistats/kpistat-4'
    | '/kpistats/kpistat-5'
    | '/kpistats/kpistat-6'
    | '/kpistats/kpistat-7'
    | '/kpistats/kpistat-8'
    | '/kpistats/kpistat-9'
    | '/pricing-comparison/pricing-comparison-base'
    | '/pricing-comparison/pricing-comparison-blurred'
    | '/pricing-comparison/pricing-comparison-featured'
    | '/pricing-comparison/pricing-comparison-featurefilled'
    | '/pricing-comparison/pricing-comparison-highlighted'
    | '/pricing-comparison/pricing-comparison-mostpopular'
    | '/pricing-comparison/pricing-comparison-mostpopularsoft'
    | '/pricing-comparison/pricing-comparison-stickyheader'
    | '/pricing/pricing-baseprice'
    | '/pricing/pricing-blurredbackground'
    | '/pricing/pricing-featuredtier'
    | '/pricing/pricing-featuredtier-filled'
    | '/pricing/pricing-mostpopularhighlighted'
    | '/pricing/pricing-mostpopulartier'
    | '/pricing/pricing-mostpopulartierfilled'
    | '/pricing/pricing-simpleprice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BannerLazyRoute: typeof BannerLazyRoute
  BarsLazyRoute: typeof BarsLazyRouteWithChildren
  ChartsLazyRoute: typeof ChartsLazyRouteWithChildren
  CookiesLazyRoute: typeof CookiesLazyRouteWithChildren
  FaqsLazyRoute: typeof FaqsLazyRouteWithChildren
  FooterLazyRoute: typeof FooterLazyRoute
  GraphLazyRoute: typeof GraphLazyRouteWithChildren
  HerosectionLazyRoute: typeof HerosectionLazyRouteWithChildren
  KpistatsLazyRoute: typeof KpistatsLazyRouteWithChildren
  PricingLazyRoute: typeof PricingLazyRouteWithChildren
  PricingComparisonLazyRoute: typeof PricingComparisonLazyRouteWithChildren
  TeamsLazyRoute: typeof TeamsLazyRoute
  TestLazyRoute: typeof TestLazyRoute
  BannersBannerBasicLazyRoute: typeof BannersBannerBasicLazyRoute
  BannersBannerBetweenjustifiedLazyRoute: typeof BannersBannerBetweenjustifiedLazyRoute
  BannersBannerBrandcolorsLazyRoute: typeof BannersBannerBrandcolorsLazyRoute
  BannersBannerFloatLazyRoute: typeof BannersBannerFloatLazyRoute
  BannersBannerFloatbottomLazyRoute: typeof BannersBannerFloatbottomLazyRoute
  BannersBannerFloatbottomcenterLazyRoute: typeof BannersBannerFloatbottomcenterLazyRoute
  BannersBannerGradientLazyRoute: typeof BannersBannerGradientLazyRoute
  BannersBannerInvertedLazyRoute: typeof BannersBannerInvertedLazyRoute
  FootersFooterColumnLazyRoute: typeof FootersFooterColumnLazyRoute
  FootersFooterNewsletterLazyRoute: typeof FootersFooterNewsletterLazyRoute
  FootersFooterSocialLinkLazyRoute: typeof FootersFooterSocialLinkLazyRoute
  FootersFooterThemeLazyRoute: typeof FootersFooterThemeLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-comparison': {
      id: '/pricing-comparison'
      path: '/pricing-comparison'
      fullPath: '/pricing-comparison'
      preLoaderRoute: typeof PricingComparisonLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpistats': {
      id: '/kpistats'
      path: '/kpistats'
      fullPath: '/kpistats'
      preLoaderRoute: typeof KpistatsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herosection': {
      id: '/herosection'
      path: '/herosection'
      fullPath: '/herosection'
      preLoaderRoute: typeof HerosectionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer': {
      id: '/footer'
      path: '/footer'
      fullPath: '/footer'
      preLoaderRoute: typeof FooterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bars': {
      id: '/bars'
      path: '/bars'
      fullPath: '/bars'
      preLoaderRoute: typeof BarsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banner': {
      id: '/banner'
      path: '/banner'
      fullPath: '/banner'
      preLoaderRoute: typeof BannerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/pricing-simpleprice': {
      id: '/pricing/pricing-simpleprice'
      path: '/pricing-simpleprice'
      fullPath: '/pricing/pricing-simpleprice'
      preLoaderRoute: typeof PricingPricingSimplepriceLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-mostpopulartierfilled': {
      id: '/pricing/pricing-mostpopulartierfilled'
      path: '/pricing-mostpopulartierfilled'
      fullPath: '/pricing/pricing-mostpopulartierfilled'
      preLoaderRoute: typeof PricingPricingMostpopulartierfilledLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-mostpopulartier': {
      id: '/pricing/pricing-mostpopulartier'
      path: '/pricing-mostpopulartier'
      fullPath: '/pricing/pricing-mostpopulartier'
      preLoaderRoute: typeof PricingPricingMostpopulartierLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-mostpopularhighlighted': {
      id: '/pricing/pricing-mostpopularhighlighted'
      path: '/pricing-mostpopularhighlighted'
      fullPath: '/pricing/pricing-mostpopularhighlighted'
      preLoaderRoute: typeof PricingPricingMostpopularhighlightedLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-featuredtier-filled': {
      id: '/pricing/pricing-featuredtier-filled'
      path: '/pricing-featuredtier-filled'
      fullPath: '/pricing/pricing-featuredtier-filled'
      preLoaderRoute: typeof PricingPricingFeaturedtierFilledLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-featuredtier': {
      id: '/pricing/pricing-featuredtier'
      path: '/pricing-featuredtier'
      fullPath: '/pricing/pricing-featuredtier'
      preLoaderRoute: typeof PricingPricingFeaturedtierLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-blurredbackground': {
      id: '/pricing/pricing-blurredbackground'
      path: '/pricing-blurredbackground'
      fullPath: '/pricing/pricing-blurredbackground'
      preLoaderRoute: typeof PricingPricingBlurredbackgroundLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing/pricing-baseprice': {
      id: '/pricing/pricing-baseprice'
      path: '/pricing-baseprice'
      fullPath: '/pricing/pricing-baseprice'
      preLoaderRoute: typeof PricingPricingBasepriceLazyRouteImport
      parentRoute: typeof PricingLazyRoute
    }
    '/pricing-comparison/pricing-comparison-stickyheader': {
      id: '/pricing-comparison/pricing-comparison-stickyheader'
      path: '/pricing-comparison-stickyheader'
      fullPath: '/pricing-comparison/pricing-comparison-stickyheader'
      preLoaderRoute: typeof PricingComparisonPricingComparisonStickyheaderLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-mostpopularsoft': {
      id: '/pricing-comparison/pricing-comparison-mostpopularsoft'
      path: '/pricing-comparison-mostpopularsoft'
      fullPath: '/pricing-comparison/pricing-comparison-mostpopularsoft'
      preLoaderRoute: typeof PricingComparisonPricingComparisonMostpopularsoftLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-mostpopular': {
      id: '/pricing-comparison/pricing-comparison-mostpopular'
      path: '/pricing-comparison-mostpopular'
      fullPath: '/pricing-comparison/pricing-comparison-mostpopular'
      preLoaderRoute: typeof PricingComparisonPricingComparisonMostpopularLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-highlighted': {
      id: '/pricing-comparison/pricing-comparison-highlighted'
      path: '/pricing-comparison-highlighted'
      fullPath: '/pricing-comparison/pricing-comparison-highlighted'
      preLoaderRoute: typeof PricingComparisonPricingComparisonHighlightedLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-featurefilled': {
      id: '/pricing-comparison/pricing-comparison-featurefilled'
      path: '/pricing-comparison-featurefilled'
      fullPath: '/pricing-comparison/pricing-comparison-featurefilled'
      preLoaderRoute: typeof PricingComparisonPricingComparisonFeaturefilledLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-featured': {
      id: '/pricing-comparison/pricing-comparison-featured'
      path: '/pricing-comparison-featured'
      fullPath: '/pricing-comparison/pricing-comparison-featured'
      preLoaderRoute: typeof PricingComparisonPricingComparisonFeaturedLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-blurred': {
      id: '/pricing-comparison/pricing-comparison-blurred'
      path: '/pricing-comparison-blurred'
      fullPath: '/pricing-comparison/pricing-comparison-blurred'
      preLoaderRoute: typeof PricingComparisonPricingComparisonBlurredLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/pricing-comparison/pricing-comparison-base': {
      id: '/pricing-comparison/pricing-comparison-base'
      path: '/pricing-comparison-base'
      fullPath: '/pricing-comparison/pricing-comparison-base'
      preLoaderRoute: typeof PricingComparisonPricingComparisonBaseLazyRouteImport
      parentRoute: typeof PricingComparisonLazyRoute
    }
    '/kpistats/kpistat-9': {
      id: '/kpistats/kpistat-9'
      path: '/kpistat-9'
      fullPath: '/kpistats/kpistat-9'
      preLoaderRoute: typeof KpistatsKpistat9LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-8': {
      id: '/kpistats/kpistat-8'
      path: '/kpistat-8'
      fullPath: '/kpistats/kpistat-8'
      preLoaderRoute: typeof KpistatsKpistat8LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-7': {
      id: '/kpistats/kpistat-7'
      path: '/kpistat-7'
      fullPath: '/kpistats/kpistat-7'
      preLoaderRoute: typeof KpistatsKpistat7LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-6': {
      id: '/kpistats/kpistat-6'
      path: '/kpistat-6'
      fullPath: '/kpistats/kpistat-6'
      preLoaderRoute: typeof KpistatsKpistat6LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-5': {
      id: '/kpistats/kpistat-5'
      path: '/kpistat-5'
      fullPath: '/kpistats/kpistat-5'
      preLoaderRoute: typeof KpistatsKpistat5LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-4': {
      id: '/kpistats/kpistat-4'
      path: '/kpistat-4'
      fullPath: '/kpistats/kpistat-4'
      preLoaderRoute: typeof KpistatsKpistat4LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-3': {
      id: '/kpistats/kpistat-3'
      path: '/kpistat-3'
      fullPath: '/kpistats/kpistat-3'
      preLoaderRoute: typeof KpistatsKpistat3LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-2': {
      id: '/kpistats/kpistat-2'
      path: '/kpistat-2'
      fullPath: '/kpistats/kpistat-2'
      preLoaderRoute: typeof KpistatsKpistat2LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/kpistats/kpistat-1': {
      id: '/kpistats/kpistat-1'
      path: '/kpistat-1'
      fullPath: '/kpistats/kpistat-1'
      preLoaderRoute: typeof KpistatsKpistat1LazyRouteImport
      parentRoute: typeof KpistatsLazyRoute
    }
    '/herosection/herosection-skewed': {
      id: '/herosection/herosection-skewed'
      path: '/herosection-skewed'
      fullPath: '/herosection/herosection-skewed'
      preLoaderRoute: typeof HerosectionHerosectionSkewedLazyRouteImport
      parentRoute: typeof HerosectionLazyRoute
    }
    '/herosection/herosection-screenshot': {
      id: '/herosection/herosection-screenshot'
      path: '/herosection-screenshot'
      fullPath: '/herosection/herosection-screenshot'
      preLoaderRoute: typeof HerosectionHerosectionScreenshotLazyRouteImport
      parentRoute: typeof HerosectionLazyRoute
    }
    '/herosection/herosection-centerednavbar': {
      id: '/herosection/herosection-centerednavbar'
      path: '/herosection-centerednavbar'
      fullPath: '/herosection/herosection-centerednavbar'
      preLoaderRoute: typeof HerosectionHerosectionCenterednavbarLazyRouteImport
      parentRoute: typeof HerosectionLazyRoute
    }
    '/herosection/herosection-basic': {
      id: '/herosection/herosection-basic'
      path: '/herosection-basic'
      fullPath: '/herosection/herosection-basic'
      preLoaderRoute: typeof HerosectionHerosectionBasicLazyRouteImport
      parentRoute: typeof HerosectionLazyRoute
    }
    '/graph/graph-2': {
      id: '/graph/graph-2'
      path: '/graph-2'
      fullPath: '/graph/graph-2'
      preLoaderRoute: typeof GraphGraph2LazyRouteImport
      parentRoute: typeof GraphLazyRoute
    }
    '/graph/graph-1': {
      id: '/graph/graph-1'
      path: '/graph-1'
      fullPath: '/graph/graph-1'
      preLoaderRoute: typeof GraphGraph1LazyRouteImport
      parentRoute: typeof GraphLazyRoute
    }
    '/footers/footer-theme': {
      id: '/footers/footer-theme'
      path: '/footers/footer-theme'
      fullPath: '/footers/footer-theme'
      preLoaderRoute: typeof FootersFooterThemeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footers/footer-socialLink': {
      id: '/footers/footer-socialLink'
      path: '/footers/footer-socialLink'
      fullPath: '/footers/footer-socialLink'
      preLoaderRoute: typeof FootersFooterSocialLinkLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footers/footer-newsletter': {
      id: '/footers/footer-newsletter'
      path: '/footers/footer-newsletter'
      fullPath: '/footers/footer-newsletter'
      preLoaderRoute: typeof FootersFooterNewsletterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footers/footer-column': {
      id: '/footers/footer-column'
      path: '/footers/footer-column'
      fullPath: '/footers/footer-column'
      preLoaderRoute: typeof FootersFooterColumnLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/twocolumn-faqs': {
      id: '/faqs/twocolumn-faqs'
      path: '/twocolumn-faqs'
      fullPath: '/faqs/twocolumn-faqs'
      preLoaderRoute: typeof FaqsTwocolumnFaqsLazyRouteImport
      parentRoute: typeof FaqsLazyRoute
    }
    '/faqs/faqs-divider': {
      id: '/faqs/faqs-divider'
      path: '/faqs-divider'
      fullPath: '/faqs/faqs-divider'
      preLoaderRoute: typeof FaqsFaqsDividerLazyRouteImport
      parentRoute: typeof FaqsLazyRoute
    }
    '/faqs/centered-faqs': {
      id: '/faqs/centered-faqs'
      path: '/centered-faqs'
      fullPath: '/faqs/centered-faqs'
      preLoaderRoute: typeof FaqsCenteredFaqsLazyRouteImport
      parentRoute: typeof FaqsLazyRoute
    }
    '/faqs/basic-faqs': {
      id: '/faqs/basic-faqs'
      path: '/basic-faqs'
      fullPath: '/faqs/basic-faqs'
      preLoaderRoute: typeof FaqsBasicFaqsLazyRouteImport
      parentRoute: typeof FaqsLazyRoute
    }
    '/cookies/cookies-verticalbuttons': {
      id: '/cookies/cookies-verticalbuttons'
      path: '/cookies-verticalbuttons'
      fullPath: '/cookies/cookies-verticalbuttons'
      preLoaderRoute: typeof CookiesCookiesVerticalbuttonsLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-fullwidth': {
      id: '/cookies/cookies-fullwidth'
      path: '/cookies-fullwidth'
      fullPath: '/cookies/cookies-fullwidth'
      preLoaderRoute: typeof CookiesCookiesFullwidthLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-floatingbottom': {
      id: '/cookies/cookies-floatingbottom'
      path: '/cookies-floatingbottom'
      fullPath: '/cookies/cookies-floatingbottom'
      preLoaderRoute: typeof CookiesCookiesFloatingbottomLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-brandcolors': {
      id: '/cookies/cookies-brandcolors'
      path: '/cookies-brandcolors'
      fullPath: '/cookies/cookies-brandcolors'
      preLoaderRoute: typeof CookiesCookiesBrandcolorsLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-bottomfixed': {
      id: '/cookies/cookies-bottomfixed'
      path: '/cookies-bottomfixed'
      fullPath: '/cookies/cookies-bottomfixed'
      preLoaderRoute: typeof CookiesCookiesBottomfixedLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-bottomcenter': {
      id: '/cookies/cookies-bottomcenter'
      path: '/cookies-bottomcenter'
      fullPath: '/cookies/cookies-bottomcenter'
      preLoaderRoute: typeof CookiesCookiesBottomcenterLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-basic': {
      id: '/cookies/cookies-basic'
      path: '/cookies-basic'
      fullPath: '/cookies/cookies-basic'
      preLoaderRoute: typeof CookiesCookiesBasicLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/cookies/cookies-animated': {
      id: '/cookies/cookies-animated'
      path: '/cookies-animated'
      fullPath: '/cookies/cookies-animated'
      preLoaderRoute: typeof CookiesCookiesAnimatedLazyRouteImport
      parentRoute: typeof CookiesLazyRoute
    }
    '/charts/circle-6': {
      id: '/charts/circle-6'
      path: '/circle-6'
      fullPath: '/charts/circle-6'
      preLoaderRoute: typeof ChartsCircle6LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-5': {
      id: '/charts/circle-5'
      path: '/circle-5'
      fullPath: '/charts/circle-5'
      preLoaderRoute: typeof ChartsCircle5LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-4': {
      id: '/charts/circle-4'
      path: '/circle-4'
      fullPath: '/charts/circle-4'
      preLoaderRoute: typeof ChartsCircle4LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-3': {
      id: '/charts/circle-3'
      path: '/circle-3'
      fullPath: '/charts/circle-3'
      preLoaderRoute: typeof ChartsCircle3LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-2': {
      id: '/charts/circle-2'
      path: '/circle-2'
      fullPath: '/charts/circle-2'
      preLoaderRoute: typeof ChartsCircle2LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/charts/circle-1': {
      id: '/charts/circle-1'
      path: '/circle-1'
      fullPath: '/charts/circle-1'
      preLoaderRoute: typeof ChartsCircle1LazyRouteImport
      parentRoute: typeof ChartsLazyRoute
    }
    '/bars/bars-4': {
      id: '/bars/bars-4'
      path: '/bars-4'
      fullPath: '/bars/bars-4'
      preLoaderRoute: typeof BarsBars4LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-3': {
      id: '/bars/bars-3'
      path: '/bars-3'
      fullPath: '/bars/bars-3'
      preLoaderRoute: typeof BarsBars3LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-2': {
      id: '/bars/bars-2'
      path: '/bars-2'
      fullPath: '/bars/bars-2'
      preLoaderRoute: typeof BarsBars2LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/bars/bars-1': {
      id: '/bars/bars-1'
      path: '/bars-1'
      fullPath: '/bars/bars-1'
      preLoaderRoute: typeof BarsBars1LazyRouteImport
      parentRoute: typeof BarsLazyRoute
    }
    '/banners/banner-inverted': {
      id: '/banners/banner-inverted'
      path: '/banners/banner-inverted'
      fullPath: '/banners/banner-inverted'
      preLoaderRoute: typeof BannersBannerInvertedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-gradient': {
      id: '/banners/banner-gradient'
      path: '/banners/banner-gradient'
      fullPath: '/banners/banner-gradient'
      preLoaderRoute: typeof BannersBannerGradientLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-floatbottomcenter': {
      id: '/banners/banner-floatbottomcenter'
      path: '/banners/banner-floatbottomcenter'
      fullPath: '/banners/banner-floatbottomcenter'
      preLoaderRoute: typeof BannersBannerFloatbottomcenterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-floatbottom': {
      id: '/banners/banner-floatbottom'
      path: '/banners/banner-floatbottom'
      fullPath: '/banners/banner-floatbottom'
      preLoaderRoute: typeof BannersBannerFloatbottomLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-float': {
      id: '/banners/banner-float'
      path: '/banners/banner-float'
      fullPath: '/banners/banner-float'
      preLoaderRoute: typeof BannersBannerFloatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-brandcolors': {
      id: '/banners/banner-brandcolors'
      path: '/banners/banner-brandcolors'
      fullPath: '/banners/banner-brandcolors'
      preLoaderRoute: typeof BannersBannerBrandcolorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-betweenjustified': {
      id: '/banners/banner-betweenjustified'
      path: '/banners/banner-betweenjustified'
      fullPath: '/banners/banner-betweenjustified'
      preLoaderRoute: typeof BannersBannerBetweenjustifiedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners/banner-basic': {
      id: '/banners/banner-basic'
      path: '/banners/banner-basic'
      fullPath: '/banners/banner-basic'
      preLoaderRoute: typeof BannersBannerBasicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BarsLazyRouteChildren {
  BarsBars1LazyRoute: typeof BarsBars1LazyRoute
  BarsBars2LazyRoute: typeof BarsBars2LazyRoute
  BarsBars3LazyRoute: typeof BarsBars3LazyRoute
  BarsBars4LazyRoute: typeof BarsBars4LazyRoute
}

const BarsLazyRouteChildren: BarsLazyRouteChildren = {
  BarsBars1LazyRoute: BarsBars1LazyRoute,
  BarsBars2LazyRoute: BarsBars2LazyRoute,
  BarsBars3LazyRoute: BarsBars3LazyRoute,
  BarsBars4LazyRoute: BarsBars4LazyRoute,
}

const BarsLazyRouteWithChildren = BarsLazyRoute._addFileChildren(
  BarsLazyRouteChildren,
)

interface ChartsLazyRouteChildren {
  ChartsCircle1LazyRoute: typeof ChartsCircle1LazyRoute
  ChartsCircle2LazyRoute: typeof ChartsCircle2LazyRoute
  ChartsCircle3LazyRoute: typeof ChartsCircle3LazyRoute
  ChartsCircle4LazyRoute: typeof ChartsCircle4LazyRoute
  ChartsCircle5LazyRoute: typeof ChartsCircle5LazyRoute
  ChartsCircle6LazyRoute: typeof ChartsCircle6LazyRoute
}

const ChartsLazyRouteChildren: ChartsLazyRouteChildren = {
  ChartsCircle1LazyRoute: ChartsCircle1LazyRoute,
  ChartsCircle2LazyRoute: ChartsCircle2LazyRoute,
  ChartsCircle3LazyRoute: ChartsCircle3LazyRoute,
  ChartsCircle4LazyRoute: ChartsCircle4LazyRoute,
  ChartsCircle5LazyRoute: ChartsCircle5LazyRoute,
  ChartsCircle6LazyRoute: ChartsCircle6LazyRoute,
}

const ChartsLazyRouteWithChildren = ChartsLazyRoute._addFileChildren(
  ChartsLazyRouteChildren,
)

interface CookiesLazyRouteChildren {
  CookiesCookiesAnimatedLazyRoute: typeof CookiesCookiesAnimatedLazyRoute
  CookiesCookiesBasicLazyRoute: typeof CookiesCookiesBasicLazyRoute
  CookiesCookiesBottomcenterLazyRoute: typeof CookiesCookiesBottomcenterLazyRoute
  CookiesCookiesBottomfixedLazyRoute: typeof CookiesCookiesBottomfixedLazyRoute
  CookiesCookiesBrandcolorsLazyRoute: typeof CookiesCookiesBrandcolorsLazyRoute
  CookiesCookiesFloatingbottomLazyRoute: typeof CookiesCookiesFloatingbottomLazyRoute
  CookiesCookiesFullwidthLazyRoute: typeof CookiesCookiesFullwidthLazyRoute
  CookiesCookiesVerticalbuttonsLazyRoute: typeof CookiesCookiesVerticalbuttonsLazyRoute
}

const CookiesLazyRouteChildren: CookiesLazyRouteChildren = {
  CookiesCookiesAnimatedLazyRoute: CookiesCookiesAnimatedLazyRoute,
  CookiesCookiesBasicLazyRoute: CookiesCookiesBasicLazyRoute,
  CookiesCookiesBottomcenterLazyRoute: CookiesCookiesBottomcenterLazyRoute,
  CookiesCookiesBottomfixedLazyRoute: CookiesCookiesBottomfixedLazyRoute,
  CookiesCookiesBrandcolorsLazyRoute: CookiesCookiesBrandcolorsLazyRoute,
  CookiesCookiesFloatingbottomLazyRoute: CookiesCookiesFloatingbottomLazyRoute,
  CookiesCookiesFullwidthLazyRoute: CookiesCookiesFullwidthLazyRoute,
  CookiesCookiesVerticalbuttonsLazyRoute:
    CookiesCookiesVerticalbuttonsLazyRoute,
}

const CookiesLazyRouteWithChildren = CookiesLazyRoute._addFileChildren(
  CookiesLazyRouteChildren,
)

interface FaqsLazyRouteChildren {
  FaqsBasicFaqsLazyRoute: typeof FaqsBasicFaqsLazyRoute
  FaqsCenteredFaqsLazyRoute: typeof FaqsCenteredFaqsLazyRoute
  FaqsFaqsDividerLazyRoute: typeof FaqsFaqsDividerLazyRoute
  FaqsTwocolumnFaqsLazyRoute: typeof FaqsTwocolumnFaqsLazyRoute
}

const FaqsLazyRouteChildren: FaqsLazyRouteChildren = {
  FaqsBasicFaqsLazyRoute: FaqsBasicFaqsLazyRoute,
  FaqsCenteredFaqsLazyRoute: FaqsCenteredFaqsLazyRoute,
  FaqsFaqsDividerLazyRoute: FaqsFaqsDividerLazyRoute,
  FaqsTwocolumnFaqsLazyRoute: FaqsTwocolumnFaqsLazyRoute,
}

const FaqsLazyRouteWithChildren = FaqsLazyRoute._addFileChildren(
  FaqsLazyRouteChildren,
)

interface GraphLazyRouteChildren {
  GraphGraph1LazyRoute: typeof GraphGraph1LazyRoute
  GraphGraph2LazyRoute: typeof GraphGraph2LazyRoute
}

const GraphLazyRouteChildren: GraphLazyRouteChildren = {
  GraphGraph1LazyRoute: GraphGraph1LazyRoute,
  GraphGraph2LazyRoute: GraphGraph2LazyRoute,
}

const GraphLazyRouteWithChildren = GraphLazyRoute._addFileChildren(
  GraphLazyRouteChildren,
)

interface HerosectionLazyRouteChildren {
  HerosectionHerosectionBasicLazyRoute: typeof HerosectionHerosectionBasicLazyRoute
  HerosectionHerosectionCenterednavbarLazyRoute: typeof HerosectionHerosectionCenterednavbarLazyRoute
  HerosectionHerosectionScreenshotLazyRoute: typeof HerosectionHerosectionScreenshotLazyRoute
  HerosectionHerosectionSkewedLazyRoute: typeof HerosectionHerosectionSkewedLazyRoute
}

const HerosectionLazyRouteChildren: HerosectionLazyRouteChildren = {
  HerosectionHerosectionBasicLazyRoute: HerosectionHerosectionBasicLazyRoute,
  HerosectionHerosectionCenterednavbarLazyRoute:
    HerosectionHerosectionCenterednavbarLazyRoute,
  HerosectionHerosectionScreenshotLazyRoute:
    HerosectionHerosectionScreenshotLazyRoute,
  HerosectionHerosectionSkewedLazyRoute: HerosectionHerosectionSkewedLazyRoute,
}

const HerosectionLazyRouteWithChildren = HerosectionLazyRoute._addFileChildren(
  HerosectionLazyRouteChildren,
)

interface KpistatsLazyRouteChildren {
  KpistatsKpistat1LazyRoute: typeof KpistatsKpistat1LazyRoute
  KpistatsKpistat2LazyRoute: typeof KpistatsKpistat2LazyRoute
  KpistatsKpistat3LazyRoute: typeof KpistatsKpistat3LazyRoute
  KpistatsKpistat4LazyRoute: typeof KpistatsKpistat4LazyRoute
  KpistatsKpistat5LazyRoute: typeof KpistatsKpistat5LazyRoute
  KpistatsKpistat6LazyRoute: typeof KpistatsKpistat6LazyRoute
  KpistatsKpistat7LazyRoute: typeof KpistatsKpistat7LazyRoute
  KpistatsKpistat8LazyRoute: typeof KpistatsKpistat8LazyRoute
  KpistatsKpistat9LazyRoute: typeof KpistatsKpistat9LazyRoute
}

const KpistatsLazyRouteChildren: KpistatsLazyRouteChildren = {
  KpistatsKpistat1LazyRoute: KpistatsKpistat1LazyRoute,
  KpistatsKpistat2LazyRoute: KpistatsKpistat2LazyRoute,
  KpistatsKpistat3LazyRoute: KpistatsKpistat3LazyRoute,
  KpistatsKpistat4LazyRoute: KpistatsKpistat4LazyRoute,
  KpistatsKpistat5LazyRoute: KpistatsKpistat5LazyRoute,
  KpistatsKpistat6LazyRoute: KpistatsKpistat6LazyRoute,
  KpistatsKpistat7LazyRoute: KpistatsKpistat7LazyRoute,
  KpistatsKpistat8LazyRoute: KpistatsKpistat8LazyRoute,
  KpistatsKpistat9LazyRoute: KpistatsKpistat9LazyRoute,
}

const KpistatsLazyRouteWithChildren = KpistatsLazyRoute._addFileChildren(
  KpistatsLazyRouteChildren,
)

interface PricingLazyRouteChildren {
  PricingPricingBasepriceLazyRoute: typeof PricingPricingBasepriceLazyRoute
  PricingPricingBlurredbackgroundLazyRoute: typeof PricingPricingBlurredbackgroundLazyRoute
  PricingPricingFeaturedtierLazyRoute: typeof PricingPricingFeaturedtierLazyRoute
  PricingPricingFeaturedtierFilledLazyRoute: typeof PricingPricingFeaturedtierFilledLazyRoute
  PricingPricingMostpopularhighlightedLazyRoute: typeof PricingPricingMostpopularhighlightedLazyRoute
  PricingPricingMostpopulartierLazyRoute: typeof PricingPricingMostpopulartierLazyRoute
  PricingPricingMostpopulartierfilledLazyRoute: typeof PricingPricingMostpopulartierfilledLazyRoute
  PricingPricingSimplepriceLazyRoute: typeof PricingPricingSimplepriceLazyRoute
}

const PricingLazyRouteChildren: PricingLazyRouteChildren = {
  PricingPricingBasepriceLazyRoute: PricingPricingBasepriceLazyRoute,
  PricingPricingBlurredbackgroundLazyRoute:
    PricingPricingBlurredbackgroundLazyRoute,
  PricingPricingFeaturedtierLazyRoute: PricingPricingFeaturedtierLazyRoute,
  PricingPricingFeaturedtierFilledLazyRoute:
    PricingPricingFeaturedtierFilledLazyRoute,
  PricingPricingMostpopularhighlightedLazyRoute:
    PricingPricingMostpopularhighlightedLazyRoute,
  PricingPricingMostpopulartierLazyRoute:
    PricingPricingMostpopulartierLazyRoute,
  PricingPricingMostpopulartierfilledLazyRoute:
    PricingPricingMostpopulartierfilledLazyRoute,
  PricingPricingSimplepriceLazyRoute: PricingPricingSimplepriceLazyRoute,
}

const PricingLazyRouteWithChildren = PricingLazyRoute._addFileChildren(
  PricingLazyRouteChildren,
)

interface PricingComparisonLazyRouteChildren {
  PricingComparisonPricingComparisonBaseLazyRoute: typeof PricingComparisonPricingComparisonBaseLazyRoute
  PricingComparisonPricingComparisonBlurredLazyRoute: typeof PricingComparisonPricingComparisonBlurredLazyRoute
  PricingComparisonPricingComparisonFeaturedLazyRoute: typeof PricingComparisonPricingComparisonFeaturedLazyRoute
  PricingComparisonPricingComparisonFeaturefilledLazyRoute: typeof PricingComparisonPricingComparisonFeaturefilledLazyRoute
  PricingComparisonPricingComparisonHighlightedLazyRoute: typeof PricingComparisonPricingComparisonHighlightedLazyRoute
  PricingComparisonPricingComparisonMostpopularLazyRoute: typeof PricingComparisonPricingComparisonMostpopularLazyRoute
  PricingComparisonPricingComparisonMostpopularsoftLazyRoute: typeof PricingComparisonPricingComparisonMostpopularsoftLazyRoute
  PricingComparisonPricingComparisonStickyheaderLazyRoute: typeof PricingComparisonPricingComparisonStickyheaderLazyRoute
}

const PricingComparisonLazyRouteChildren: PricingComparisonLazyRouteChildren = {
  PricingComparisonPricingComparisonBaseLazyRoute:
    PricingComparisonPricingComparisonBaseLazyRoute,
  PricingComparisonPricingComparisonBlurredLazyRoute:
    PricingComparisonPricingComparisonBlurredLazyRoute,
  PricingComparisonPricingComparisonFeaturedLazyRoute:
    PricingComparisonPricingComparisonFeaturedLazyRoute,
  PricingComparisonPricingComparisonFeaturefilledLazyRoute:
    PricingComparisonPricingComparisonFeaturefilledLazyRoute,
  PricingComparisonPricingComparisonHighlightedLazyRoute:
    PricingComparisonPricingComparisonHighlightedLazyRoute,
  PricingComparisonPricingComparisonMostpopularLazyRoute:
    PricingComparisonPricingComparisonMostpopularLazyRoute,
  PricingComparisonPricingComparisonMostpopularsoftLazyRoute:
    PricingComparisonPricingComparisonMostpopularsoftLazyRoute,
  PricingComparisonPricingComparisonStickyheaderLazyRoute:
    PricingComparisonPricingComparisonStickyheaderLazyRoute,
}

const PricingComparisonLazyRouteWithChildren =
  PricingComparisonLazyRoute._addFileChildren(
    PricingComparisonLazyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BannerLazyRoute: BannerLazyRoute,
  BarsLazyRoute: BarsLazyRouteWithChildren,
  ChartsLazyRoute: ChartsLazyRouteWithChildren,
  CookiesLazyRoute: CookiesLazyRouteWithChildren,
  FaqsLazyRoute: FaqsLazyRouteWithChildren,
  FooterLazyRoute: FooterLazyRoute,
  GraphLazyRoute: GraphLazyRouteWithChildren,
  HerosectionLazyRoute: HerosectionLazyRouteWithChildren,
  KpistatsLazyRoute: KpistatsLazyRouteWithChildren,
  PricingLazyRoute: PricingLazyRouteWithChildren,
  PricingComparisonLazyRoute: PricingComparisonLazyRouteWithChildren,
  TeamsLazyRoute: TeamsLazyRoute,
  TestLazyRoute: TestLazyRoute,
  BannersBannerBasicLazyRoute: BannersBannerBasicLazyRoute,
  BannersBannerBetweenjustifiedLazyRoute:
    BannersBannerBetweenjustifiedLazyRoute,
  BannersBannerBrandcolorsLazyRoute: BannersBannerBrandcolorsLazyRoute,
  BannersBannerFloatLazyRoute: BannersBannerFloatLazyRoute,
  BannersBannerFloatbottomLazyRoute: BannersBannerFloatbottomLazyRoute,
  BannersBannerFloatbottomcenterLazyRoute:
    BannersBannerFloatbottomcenterLazyRoute,
  BannersBannerGradientLazyRoute: BannersBannerGradientLazyRoute,
  BannersBannerInvertedLazyRoute: BannersBannerInvertedLazyRoute,
  FootersFooterColumnLazyRoute: FootersFooterColumnLazyRoute,
  FootersFooterNewsletterLazyRoute: FootersFooterNewsletterLazyRoute,
  FootersFooterSocialLinkLazyRoute: FootersFooterSocialLinkLazyRoute,
  FootersFooterThemeLazyRoute: FootersFooterThemeLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
